---
title: "Open Refine with Talis Aspire"
author: "D. Spence"
date: "28th of September, 2021"
output: 
  html_document:
    theme: darkly
    toc: yes
    toc_float:
      collapsed: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction to Open Refine

Open Refine, formerly known as Google Refine is a tool for exploring data sets, transforming it into something useful and enhancing it into something more useful. The goal of this guide is to explain the basics of Open Refine using Talis Aspire data as an example. Open Refine supports MARC so it can also be used when cataloguing. 

I have been using Open Refine to proactively find problems in reading lists and fix them procedurally. On the reports tab of Talis reading lists you can export a list of all published items in a comma separated values files. This can be then be imported into Open Refine. Below I have included a table explaining what each of the fields translates to.

## Installing Open Refine
The instructions to install Open Refine can be found on the [Open Refine download page](https://openrefine.org/download.html). It supports Windows, Mac and Linux and runs in your web browser. I have had success running it at home and on office computers, if you do not know whether you have Java installed on Windows the version that comes bundled with Java is the easiest way to get started. As most staff are no longer permitted to install software on campus computers I have requested IT Services add OpenRefine to the [university software hub](https://software.essex.ac.uk) which is currently in progress as of September 2021.

## Downloading Talis Aspire data

Data can be downloaded from [Talis Aspire Reports](https://essex.rl.talis.com/reports/523E347F-38CF-E58D-929C-326B7FF25E75.html). For this guide I have been focusing on the All List Items section as my role focuses on checking lists for errors. It is worth bearing in mind that larger data sets require powerful computers. When I tried to import all 603,000 items (at the time of writing) my computer seized up due to a lack of ram. By default the software caps out at 1GB of ram, jumping up to 2GB allowed me to import the full data set. Instructions on how to do this can be found in the [Using OpenRefine book](https://subscription.packtpub.com/book/big_data_and_business_intelligence/9781783289080/1/ch01lvl1sec15/recipe-7-going-for-more-memory). It is best practice to only work on what you think you need to because actions can get sluggish. which is currently in progress as of September 2021. which is currently in progress as of September 2021. which is currently in progress as of September 2021. which is currently in progress as of September 2021. which is currently in progress as of September 2021.

Filtering list status only to only published brings it down to a manageable 129,000. Depending on the status of rollover you may want to filter by Time Period to catch items that are unpublished. Once you have your data click download CSV. This will e.mail the Talis user a link to download the CSV file. For all published items this came out to about 53 megabytes.

## Importing data into Refine

Double click the OpenRefine icon where you installed it. For me this was C:\Users\Spence\Desktop\openrefine-3.4.1\openrefine.exe. I have found searching for the app via the Windows Start menu does not open the app. This will open your default web browser to the URL [http://127.0.0.1:3333/](http://127.0.0.1:3333/) this URL only works when the OpenRefine application is running. The home screen should have a browse button to locate the all_list_items_2021_04_12.csv you just downloaded. From there just click next and create project to start playing around with your data. Once you have created a project it will be visible on the Open Project tab to the left. It saves whatever you’ve done and has a full history.

## Aspire data fields

Below I have included some notes on the fields Talis exposes. If you are familiar with editing reading lists most of this will look familiar but some of these fields are hidden. Knowing what field to filter first is the key to finding the right list items that most need attention.

| Field name             | Example                                                                    | Notes                                                                                                                                                                                                                                                                                        |                                                   |                                                                                                                                                                                         |
|------------------------|----------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Title                  | Managing and Organizations: An Introduction to Theory and Practice         | Book title, where an article has no part this field will be used instead of the below field                                                                                                                                                                                                  |                                                   |                                                                                                                                                                                         |
| Chapter/Article        | Managing Individuals                                                       | Chapter title, if used                                                                                                                                                                                                                                                                       |                                                   |                                                                                                                                                                                         |
| Item Link              | http://readinglists.essex.ac.uk/items/5d6776ef-6f78-40bb-b8f4-536d0db63e10 | Links directly to the bookmark so you can preview it                                                                                                                                                                                                                                         |                                                   |                                                                                                                                                                                         |
| Author(s)              | Clegg, Stewart R.; Kornberger, Martin; Pitsis, Tyrone S.; Mount, Matt      | Chapter author takes priority over book author, shown at top level. Sometimes this contains a full name in a single name field.                                                                                                                                                              |                                                   |                                                                                                                                                                                         |
| Editor(s)              | Bloggs, Joe                                                                | Editor is only shown when bookmark is expanded                                                                                                                                                                                                                                               |                                                   |                                                                                                                                                                                         |
| List appearance        | AB123: Some subject                                                        |                                                                                                                                                                                                                                                                                              |                                                   |                                                                                                                                                                                         |
| List Link              | http://readinglists.essex.ac.uk/lists/9C9EE6E3-556A-071E-EE4D-59CE13C35432 |                                                                                                                                                                                                                                                                                              |                                                   |                                                                                                                                                                                         |
| Type                   | Chapter, Audio Visual Document etc                                         | Selected from the Resource Type drop down menu. When a bookmark is part of a book or journal the has part type takes priority over the part of                                                                                                                                               |                                                   |                                                                                                                                                                                         |
| Importance             | Essential/Core                                                             | Blank if not set. There are some lists that contain deprecated importance such as Supplementary and Further. Helpful for finding essential items that are not available in the catalogue                                                                                                     |                                                   |                                                                                                                                                                                         |
| ISBN10                 | 1526487969                                                                 | Mostly used for books published before 2007                                                                                                                                                                                                                                                  |                                                   |                                                                                                                                                                                         |
| ISBN13                 | 9781526460103                                                              | 9781526460097                                                                                                                                                                                                                                                                                | 9781526487964                                     | 13 digit ISBN. Talis takes the book art from the first ISBN13. In testing I have found that the paperback usually is the most reliable ISBN13 to contain book art for the reading list. |
| ISSN                   | 1234-5678                                                                  | Print ISSN, often the EISSN is listed as ISSN. Electronic ISSN. Ideally split in the middle by a hyphen to ensure compatibility with Talis Aspire Digitised Content                                                                                                                          |                                                   |                                                                                                                                                                                         |
| EISSN                  | 8765-4321                                                                  | Electronic ISSN.                                                                                                                                                                                                                                                                             |                                                   |                                                                                                                                                                                         |
| LCN                    | 2304268                                                                    | Record number from the catalogue. Where a dual bookmark is used the print LCN must come first. Only works with b records Re2304268 would incorrectly link direct to the Rb2304268                                                                                                            |                                                   |                                                                                                                                                                                         |
| DOI                    | 10.4135/9781446218563                                                      | Talis generates https://0-doi-org.serlib0.essex.ac.uk/10.4135/9781446218563 for the student. A DOI will automatically create a chapter/article DOI and book DOI even if no direct DOI to the chapter exists.                                                                                 |                                                   |                                                                                                                                                                                         |
| Data of publication    | 2019                                                                       | 2019                                                                                                                                                                                                                                                                                         |                                                   |                                                                                                                                                                                         |
| Issue                  | 4, Spring                                                                  |                                                                                                                                                                                                                                                                                              |                                                   |                                                                                                                                                                                         |
| Volume                 | 87                                                                         | Often used for journals but occasionally for a series of books too. The bookmarklet sometimes get false positives for this field sometimes                                                                                                                                                   |                                                   |                                                                                                                                                                                         |
| Edition                | 5th                                                                        | Book edition                                                                                                                                                                                                                                                                                 |                                                   |                                                                                                                                                                                         |
| Start page             | 1                                                                          | Some older bookmarks feature page range in a single field                                                                                                                                                                                                                                    |                                                   |                                                                                                                                                                                         |
| End page               | 33                                                                         |                                                                                                                                                                                                                                                                                              |                                                   |                                                                                                                                                                                         |
| Publisher              | SAGE Publications Ltd.                                                     |                                                                                                                                                                                                                                                                                              |                                                   |                                                                                                                                                                                         |
| Format                 |                                                                            | Appears to be unused                                                                                                                                                                                                                                                                         |                                                   |                                                                                                                                                                                         |
| Web Address            | https://publisher.com/book/chapter1                                        | https://publisher.com/book/chapter2                                                                                                                                                                                                                                                          | Generally a copy of the Primary Web Address field |                                                                                                                                                                                         |
| Time Period            | 2021/22                                                                    | Can be used to filter by academic year                                                                                                                                                                                                                                                       |                                                   |                                                                                                                                                                                         |
| Date Added             | 2021-03-25                                                                 | Date bookmark originally added to Talis Aspire                                                                                                                                                                                                                                               |                                                   |                                                                                                                                                                                         |
| Added By               | Sloman,Albert                                                              | Person that added the bookmark to Talis Aspire                                                                                                                                                                                                                                               |                                                   |                                                                                                                                                                                         |
| Last Published         | 2021-05-14                                                                 | Date the item was last published on Talis Aspire                                                                                                                                                                                                                                             |                                                   |                                                                                                                                                                                         |
| Library Note           | Please can you purchase this as an eBook?                                  | Only visible to academic and library staff                                                                                                                                                                                                                                                   |                                                   |                                                                                                                                                                                         |
| Student Note           | Read chapter 2. This is important with regards to your assignments         | Used to provide context or instruction on a bookmark                                                                                                                                                                                                                                         |                                                   |                                                                                                                                                                                         |
| CKEY                   |                                                                            | Appears to be unused                                                                                                                                                                                                                                                                         |                                                   |                                                                                                                                                                                         |
| TADC Request ID        | 16901                                                                      | Matches the Talis Aspire Digitised Content request number                                                                                                                                                                                                                                    |                                                   |                                                                                                                                                                                         |
| TADC Request Status    | EXPIRED, LIVE, REFERRED, REJECTED, SUCCESS, WITHDRAWN                      | Status from Talis Aspire Digitised Content. Note: LIVE may be inaccessible outside of the lists term dates as speicifed in the module hierarchy                                                                                                                                              |                                                   |                                                                                                                                                                                         |
| TADC Bundle ID         | 609e95091b02c916396a12c4                                                   | Used to link to the PDF, on the list this is automatically turned into https://content.talisaspire.com/essex/bundles/609e95091b02c916396a12c4 for the student                                                                                                                                |                                                   |                                                                                                                                                                                         |
| Has Container          | tenantSections:82C5A361-B412-5E12-CADA-7756EFC4D76D                        | This relates to the structure and order the reading list. tenantSection indicates the bookmark is part of a section, like Week 9. tenantList indicates the bookmark is just on the root of the list.                                                                                         |                                                   |                                                                                                                                                                                         |
| Primary Web Address    | https://publisher.com/book/chapter1; https://publisher.com/book/chapter2   | Chapter, Article etc. URL                                                                                                                                                                                                                                                                    |                                                   |                                                                                                                                                                                         |
| Secondary Web Address  | https://publisher.com/book                                                 | Book, Journal etc. URL                                                                                                                                                                                                                                                                       |                                                   |                                                                                                                                                                                         |
| Online Resource        | https://publisher.com/book/chapter1                                        | Filled in when the Online Resource is checked on the Talis Aspire bookmark. Copied from the below instruction                                                                                                                                                                                |                                                   |                                                                                                                                                                                         |
| Online Resource Source | Web Address                                                                | Selects which of the above fields (Web Address, DOI) the VIEW ONLINE button bookmark points to. If this field is blank it means that the VIEW ONLINE button is hidden from the top of the reading list. A good way to filter out items that are not currently available or listed digitally. |                                                   |                                                                                                                                                                                         |
